version: "3.8"

services:
  nginx:
    image: nginx:latest
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lottery-vue3
    ports:
      - "80:80"
      - "443:443"
    restart: always
